// All site texts
const SiteTexts = {
    // Loader text
    loader: '   ><(((°>   Initializing… buffering…\n\n   ><(((°>   Loading text‑only UI…\n\n   ><(((°>   Please wait, fish are compiling.\n\n   ════════════════════════════════════════════\n   ⚠ WARNING: All texts and content generated by AI ⚠\n   ════════════════════════════════════════════',
    
    // Fact lines (will be shuffled)
    facts: [
        'fact(rand): prefers text-first sites; graphics join later',
        'fact(rand): midjourney omni-reference presets pinned',
        'fact(rand): built entirely by AI; code typed on pure vibe‑coding energy'
    ],
    
    // Boot sequence texts
    boot: {
        note: '# Note: All lines auto‑generated by AI — just like the entire site. Built on vibe‑coding principles.',
        earlyConsole: 'early console in decompress_kernel',
        decompressing: 'Decompressing Andrey... done',
        booting: 'Booting human kernel v1984 (RUS→UK build)',
        init: '[    0.000001] init: starting personality modules',
        creativeSubsystem: '[    0.0042] creative.subsystem ... OK',
        sarcasmDriver: '[ ok ] sarcasm_driver loaded',
        automationSubsystem: '[ ok ] automation_subsystem active',
        empathyModule: '[warn] empathy_module: unstable under pressure',
        caffeineService: '[ ok ] caffeine.service enabled',
        memory: '[info] 25 years in digital detected',
        designEngine: '[    0.0555] design_engine: penrose_tiling; surreal_logic=on',
        toolchain: '[    0.0890] toolchain: airtable=ON, cursor=ON, figma=HOT, n8n=STARTED',
        obsidianMemory: '[    0.1444] obsidian.memory: indexing thoughts ... 3419 found',
        freeletics: '[    0.2333] freeletics.kernel: 5x/week; goal=-5kg; status=RUNNING',
        nutritionTracker: '[    0.3777] nutrition_tracker: inconsistent input → recalculating macros',
        children: '[    0.6100] children_subprocesses: 2 (status=thriving)',
        humor: '[    0.9876] humor.sys: british_mode=enabled; cringe_filter=HIGH',
        realityCheck: '[    1.2345] reality_check: warning — surrealism level > recommended',
        loadingProjects: '[    1.5000] loading projects: hook_crunch, svmpx, coldxray, quantumpost ... done',
        aiAssistant: '[    1.9000] ai_assistant: integrated; mood: "reluctantly cooperative"',
        locale: '[    2.2000] locale: London; tz=UTC+0; daylight_savings=meh',
        marketingStack: '[    2.4000] marketing.stack: growth>brand>shiny',
        belief: '[    2.7000] belief: "Clear logic + open collab + playful nerdiness"',
        uptime: '[    2.8600] uptime: who_cares',
        randFact: '[    3.0400] rand.fact: hates busywork; automates on sight',
        motto: '[    3.1415] motto: Think like a system, joke like a human',
        network: '[    3.3333] network: global; roots=ideas; packet_loss=0%',
        cron: '[    3.7777] cron: write, ship, iterate, repeat',
        startupMotd: '[    4.2000] startup_motd: Hello, world!',
        verification: '[    4.4444] verification: human supervision detected — optional',
        loginPrompt: 'login: _'
    },
    
    // Commands texts
    commands: {
        about: [
            '        .-.',
            '       (o o)',
            '       | O \\',
            '        \\   \\',
            '         `~~~\'',
            'Name: Andrey Rybushkin',
            'Class: Creative Strategist / Automation Mage',
            'Alignment: Chaotic Productive',
            'Location: London Wasteland',
            'Years in Digital: 25',
            '⸻',
            'S.P.E.C.I.A.L.',
            'STRENGTH      3',
            'PERCEPTION   10',
            'ENDURANCE     7',
            'CHARISMA     10',
            'INTELLIGENCE 10',
            'AGILITY       6',
            'LUCK          9',
            '⸻',
            'SKILLS',
            '• System Design — 100/100',
            '• No‑Code Rituals (Airtable / n8n) — 98/100',
            '• Presentation Smithing — 100/100 (legendary)',
            '• Brand Lore Weaving — 95/100',
            '• Chaos Management — 200%',
            '• AI Taming — 85/100 (model complains)',
            '• Penrose Pattern Mastery — passive style buff',
            '⸻',
            'PERKS',
            '• Coffee Core Overdrive — +20% speed, −10% illusions',
            '• Vibe‑Coder — code appears first, plan comes later',
            '• Automation Instinct — any repetition → pipeline',
            '• Presentation Crit Hit — slides hit doubts',
            '• London Weather Immunity — infinite rain endurance',
            '⸻',
            'TRAITS',
            '• Cynical but Caring — stings with words, fixes with hands',
            '• Nerdy Charm — +5 interface trust',
            '• Techno‑Minimalist — text > visual noise',
            '• Dual‑Parent Multitasker — +2 wisdom',
            '• Automation‑First — manual labor condemned',
            '⸻',
            'CLIENTS & FACTIONS',
            '(generalized, no brand listing)',
            'Digital Agencies: Idolized',
            'Startups: Accepted',
            'AI Systems: Reluctantly Cooperative',
            'Humans: Mixed Feedback',
            '⸻',
            'CURRENT STATUS',
            '[ WIP / TBA / COMING SOON / STAY TUNED ]',
            'Building systems, integrating AI, deploying new projects. Nothing published early. Everything in progress.'
        ],
        clients: [
            'Worked with the loud and the legendary: MTS, McDonald\'s, Sber, Yandex, Procter & Gamble, Henkel, Huawei, Peugeot, Heineken, Nestlé, Sony, Hasbro — and a pile of startups like ColdXray, SVMPX, Hook & Crunch. If it moves, he\'s marketed it.'
        ],
        works: [
            'From underground hacker zines to Effie-winning ad campaigns, from AR concerts to logistics dashboards — 1000+ projects shipped. Style: precise logic, messy heart.'
        ],
        contacts: [
            'Mail: andrey@rybushkin',
            'Telegram: @metadron / @zavelcanal',
            'LinkedIn: /rybushkin',
            'Location: London (online everywhere)'
        ],
        game: {
            intro: [
                '$ game',
                'Launching: Vibe‑Break / Fishanoid Edition…',
                'Break the blocks. Free the fish. Pretend it\'s productive.',
                'Start the game? (y/n)'
            ],
            instructions: [
                'Controls:',
                '← → or mouse to move',
                'SPACE to launch',
                'ESC to bail out'
            ],
            fishArt: `

                 ,"(
               ////\\                           _
              (//////--,,,,,_____            ,"
            _;"""----/////_______;,,        //
__________;"o,-------------......"""""\`'-._/(
      ""'==._.__,;;;;"""           ____,.-.==
             "-.:______,...;---""/"   "    \\(
                 '-._      \`-._("  \\\\
                     '-._                    '._`,
            spacePrompt: 'Press SPACE to start.'
        },
        theme: {
            description: 'Change color, not personality.',
            themes: [
                '  • classic',
                '  • retro',
                '  • cyberpunk',
                '  • ubuntu',
                '  • gameboy',
                '  • excel',
                '  • norton',
                '  • monochrome',
                '  • tron',
                '  • macintosh'
            ],
            usage: 'Usage: theme <name>',
            example: 'Example: theme cyberpunk'
        },
        help: [
            'Help:',
            '  - Type a command and press Enter.',
            '  - Available: about, game, contacts, theme, menu, help, clear, exit',
            '  - Use ↑/↓ to navigate command history',
            '  - Type \'menu\' to print commands again'
        ],
        menu: [
            '• about',
            '• game',
            '• contacts',
            '• theme',
            '• help',
            '• clear',
            '• exit',
            '',
            '🎮 v2.0 (son edition) → https://rybushk.in/papa.html'
        ]
    },
    
    // Theme names
    themes: {
        classic: 'CLASSIC',
        retro: 'RETRO',
        cyberpunk: 'CYBERPUNK',
        ubuntu: 'UBUNTU',
        gameboy: 'GAMEBOY',
        excel: 'EXCEL',
        norton: 'NORTON',
        monochrome: 'MONOCHROME',
        tron: 'TRON',
        macintosh: 'MACINTOSH'
    }
};

